name: mirae_coletor
description: Aplicativo de colata de dados para sincronização com o mirae_agro

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0' 



dependencies:
  flutter:
    sdk: flutter

  # Banco local
  sqflite: ^2.3.0
  path: ^1.9.0

  # HTTP / API
  dio: ^5.4.0

  # Conectividade
  connectivity_plus: ^5.0.2

  # Injeção de dependência
  get_it: ^7.6.7

  # Estado
  flutter_bloc: ^8.1.4       # ou provider / riverpod

  # QR Code
  mobile_scanner: ^5.1.0        # Leitura de QR


  # Gráficos (histórico de chuva/consumo)
  fl_chart: ^0.68.0

  # Segurança
  flutter_secure_storage: ^9.2.2  # Token e URL do servidor

  # Data/Hora
  intl: ^0.19.0                 # Formatação de datas

  # Utilitários
  uuid: ^4.3.3               # IDs únicos locais
  shared_preferences: ^2.2.3 # Configs simples (ex: último sync)
  logger: ^2.3.0
  dartz: ^0.10.1             # Either para tratamento de erros

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


